### ISSUE TITLE
tpkg should not allow the user to specify the same tpkg as a dependency

### ISSUE THREAD

**Issue by jheiss** [tpkg/client#17]
right now you are allowed to create a tpkg with a dependency of itself which causes an endless cycle of tpkg calculating the dependencies.

example yaml file:

``` yaml
name: glusterfs
version: 3.0.5
package_version: 1
operatingsystem: [CentOS-5]
architecture: [x86_64]
dependencies:
  - name: glusterfs
```

I realize that it would be a rare case that a user would do this and it only came up when a coworker was creating a tpkg which installed an rpm of the same name, but the coworker forget to specify the dependency was a native dependency.

Was: https://sourceforge.net/apps/trac/tpkg/ticket/19
